moore security testing

diff --git a/.github/workflows/security.yaml b/.github/workflows/security.yaml
--- a/.github/workflows/security.yaml
+++ b/.github/workflows/security.yaml
@@ -17,9 +17,16 @@ jobs:
         uses: actions/checkout@v3
       - name: Install Snyk CLI
         run:  npm install -g snyk
-      - name: Run Snyk Code test
-        run:  snyk code test
-      - name: Check for critical vulnerabilities
+      - name: Run Snyk Static Code test
+        run:  snyk code test --json | jq '.vulnerabilities[] | select(.severity == "high" or .severity == "critical")' > snyk-code-results.json
+          if [ -s snyk-code-results.json ]
+          then
+            echo "Critical vulnerabilities found.Failing the build."
+            exit 1
+          else
+            echo "No critical vulnerabilities found."
+          fi
+      - name: Check dependencies for vulnerabilities
         run:  |
           snyk test --json | jq '.vulnerabilities[] | select(.severity == "high" or .severity == "critical")' > snyk-results.json
           if [ -s snyk-results.json ]
