check only for critical / high vulnerabilities

diff --git a/.github/workflows/security.yaml b/.github/workflows/security.yaml
--- a/.github/workflows/security.yaml
+++ b/.github/workflows/security.yaml
@@ -18,4 +18,14 @@ jobs:
       - name: Install Snyk CLI
         run:  npm install -g snyk
       - name: Run Snyk Code test
-        run:  snyk code test 
+        run:  snyk code test
+      - name: Check for critical vulnerabilities
+        run:  |
+          snyk test --json | jq '.vulnerabilities[] | select(.severity == "high" or .severity == "critical")' > snyk-results.json
+          if [ -s snyk-results.json ]
+          then
+            echo "Critical vulnerabilities found.Failing the build."
+            exit 1
+          else
+            echo "No critical vulnerabilities found."
+          fi
